#!/bin/bash
set -eo pipefail
work_root=/tmp/$1
if [ "$#" -lt 1 ]; then
  work_root+=src
fi
mkdir -p $work_root
cat | tar -xC $work_root
cd $work_root
rm -rf build
make build LOCAL=1 >&2
tar -C build -cf - .
